### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by gwhizoftv**
These directions have been tested for installing on Debian 11.

### CODE REVIEW

**Comment by benediktwerner** [comment]
As far as I can see, you mostly just added a bunch of very specific information that doesn't really apply to most people and adjusted/messed up the formatting. This container is mostly intended for Windows users and as a dev setup. If you're using Linux, it IMO makes much more sense to just follow the dev guide and set it up without Docker. At least, I don't think it make sense to mention how to set up Docker on Debian, ssh-ing into stuff, or how to setup lila on another server. If you want to run lila in production, you likely shouldn't be doing it with sbt and this container probably isn't the way to do it.

**Comment by gwhizoftv** [comment]
Good morning Benedikt,

If this repo is for Windows, let's add a docker repo for Linux, and make
yours just for Windows.

I don't see the point that Docker isn't needed on Linux but it is on
Windows. Why is that ?

Isn't the docker intended to be set up on a remote server? Or did you
intend for the Windows docker to be used on the local machine?

Regarding using sbt or something else, where are the recommendations on
that concern? I can't find them in the docs.

Many thanks,
Michael

**Comment by benediktwerner** [comment]
This is intended for Lichess development. It's not necessarily only for Windows but I don't think it makes that much sense on Linux. It's just making stuff harder there.

If you're deploying lila for production, you should build it and deploy the resulting binary, not run a whole development environment on a prod server. But this isn't really something I'm interested in or can help with much.

But you're of course very welcome to fork this repo and create one intended for deploying lila on a remote server.

**Comment by gwhizoftv** [comment]
Hi again Benedikt,

Thanks for responding. You mentioned:
"If you're deploying lila for production, you should build it and deploy
the resulting binary, not run a whole development environment on a prod
server. "
This makes a lot of sense. IN our previous messages you mentioned we should
not use sbt. Is this related to building the binary?
Does the existing lichess.org run a built binary now ? If we need to create
one, are we talking about compiling using c++ or some other language?

Many thanks,
Michael

**Comment by benediktwerner** [comment]
No, you can use sbt to compile a jar which should be runnable with just a JVM without sbt and all the other dev stuff. But as I said, it's not something I'm interested in or can help with. Other people deal with this on Lichess.

**Pull request closed without merging**
